// AUTH/USER_LOGIN
export const USER_LOGIN = 'USER_LOGIN';
export const USER_GOOGLE_LOGIN = 'USER_GOOGLE_LOGIN';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_COMPLETED = 'USER_LOGIN_COMPLETED';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGIN_RESET = 'USER_LOGIN_RESET';

// AUTH/USER_LOGOUT
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_COMPLETED = 'USER_LOGOUT_COMPLETED';
export const USER_LOGOUT_ERROR = 'USER_LOGOUT_ERROR';

// AUTH/USER_REGISTER
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_COMPLETED = 'USER_REGISTER_COMPLETED';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET';

// PETS
export const GET_PETS_REQUEST = 'GET_PETS_REQUEST';
export const GET_PETS_COMPLETED = 'GET_PETS_COMPLETED';
export const GET_PETS_ERROR = 'GET_PETS_ERROR';
export const CREATE_PET_REQUEST = 'CREATE_PET_REQUEST';
export const CREATE_PET_COMPLETED = 'CREATE_PET_COMPLETED';
export const CREATE_PET_ERROR = 'CREATE_PET_ERROR';
export const UPDATE_PET_REQUEST = 'UPDATE_PET_REQUEST';
export const UPDATE_PET_COMPLETED = 'UPDATE_PET_COMPLETED';
export const UPDATE_PET_ERROR = 'UPDATE_PET_ERROR';
export const DELETE_PET_REQUEST = 'DELETE_PET_REQUEST';
export const DELETE_PET_COMPLETED = 'DELETE_PET_COMPLETED';
export const DELETE_PET_ERROR = 'DELETE_PET_ERROR';

// ORDERS
export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_COMPLETED = 'GET_ORDERS_COMPLETED';
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR';
export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_COMPLETED = 'CREATE_ORDER_COMPLETED';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';
export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST';
export const UPDATE_ORDER_COMPLETED = 'UPDATE_ORDER_COMPLETED';
export const UPDATE_ORDER_ERROR = 'UPDATE_ORDER_ERROR';
export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST';
export const DELETE_ORDER_COMPLETED = 'DELETE_ORDER_COMPLETED';
export const DELETE_ORDER_ERROR = 'DELETE_ORDER_ERROR';

// CART
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_UPDATE_QUANTITY = 'CART_UPDATE_QUANTITY';
export const CART_CLEAR = 'CART_CLEAR';
